apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpp-dep

spec:
  selector:
    matchLabels:
      run: gpp-dep
  replicas: 1
  template:
    metadata:
      labels:
        run: gpp-dep
        namespace: default
    spec:
      containers:
      - name: gpp-dep
        image: gpp-report:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          protocol: TCP

        env:
          - name : ORACLE_USER
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: ORACLE_USER

          - name : ORACLE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: ORACLE_PASSWORD

          - name : ORACLE_HOST
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: ORACLE_HOST

          - name : ORACLE_SERVICE
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: ORACLE_SERVICE

          - name : ORACLE_PORT
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: ORACLE_PORT

          - name : ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: ENVIRONMENT

          - name : MAILTO
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: MAILTO

          - name : MAILFROM
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: MAILFROM

          - name : MAILSERVER
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: MAILSERVER

          - name : TEST
            valueFrom:
              configMapKeyRef:
                name: gppreport-config-map
                key: TEST


